// Short takeaways from the linked originals, not full translations or completed deep reads.
export const overreactedArticleSummaries: Record<string, string> = {
  "what-is-javascript-made-of": "用值、类型、变量、函数、对象和相等性搭建 JavaScript 的基础心智模型；不确定的概念先补运行机制，再记语法结论。",
  "on-let-vs-const": "const 限制变量重新赋值，不保证对象不可变。团队约定与自动检查比争论偏好更重要，不必让它阻塞代码审查。",
  "why-do-we-write-super-props": "类组件构造函数先调用 super 才能使用 this；传入 props 让构造期间的 this.props 立即可用，避免依赖 React 随后的补赋值。",
  "how-does-react-tell-a-class-from-a-function": "React 必须区分类组件的实例化与函数组件的调用；这个问题串起 new、this、原型与 class 的 JavaScript 语义。",
  "the-elements-of-ui-engineering": "UI 工程不只是会用框架，还要权衡一致性、响应速度、错误状态、交互反馈等问题。可挑真实界面逐项解释设计取舍。",
  "react-as-a-ui-runtime": "把 React 看成 UI 运行时：元素描述目标树，渲染器管理宿主实例，协调过程决定如何更新。组件是这套模型的一层抽象。",
  "how-does-setstate-know-what-to-do": "setState 不直接操作 DOM；具体更新能力由渲染器注入。这里能看清 React 核心与 React DOM 等渲染器的职责边界。",
  "why-do-react-elements-have-typeof-property": "元素上的 $$typeof 是识别 React 元素的标记，Symbol 有助于防止把不可信 JSON 误当元素渲染，体现数据边界的安全设计。",
  "why-do-hooks-rely-on-call-order": "Hooks 靠稳定的调用顺序对应状态槽位，所以不能在条件分支里随意调用；这个约束换来可组合的自定义 Hook。",
  "how-are-function-components-different-from-classes": "函数组件捕获某次渲染的 props 与 state；类组件方法可能读取可变的 this。核心区别不是性能，而是值与时间的关系。",
  "a-complete-guide-to-useeffect": "Effect 是把某次渲染与外部系统同步，不是类生命周期的替身。依赖、清理和闭包问题都要回到每次渲染各有其值来分析。",
  "making-setinterval-declarative-with-react-hooks": "setInterval 的命令式计时与 React 重渲染有阻抗不匹配。用 ref 保存最新回调、用 Effect 管理定时器，可封装可暂停的 useInterval。",
  "why-isnt-x-a-hook": "不是所有 API 都适合 Hook 化；要看它能否组合、是否便于局部理解和调试。把 memo 或 Provider 机械改成 Hook 可能破坏边界。",
  "writing-resilient-components": "比表面代码风格更重要的是组件能否承受变化：不截断数据流、随时能重渲染、不把组件当单例，并谨慎优化。",
  "before-you-memo": "性能问题先检查状态是否放得过高、慢子树能否作为 children 传入；结构调整常能减少无关渲染，memo 留给已定位的瓶颈。",
  "my-wishlist-for-hot-reloading": "理想热更新要兼顾正确性、局部性与反馈速度。先写清状态保留和失效边界，再实现工具，比只看自动刷新效果可靠。",
  "what-are-the-react-team-principles": "作者归纳的原则包括先看 UI 再定 API、由框架吸收复杂性、支持局部推理与渐进复杂度；抽象应以用户体验检验。",
  "optimized-for-change": "好的 API 不只让今天调用简洁，也要让将来的移动、复制、拆分和调试成本可控；变更能力应是一等设计指标。",
  "the-bug-o-notation": "API 也可按定位错误的成本衡量：一个值错了，需要跨多少层、查多少处？局部可追踪的数据流能降低调试复杂度。",
  "goodbye-clean-code": "过早去重与抽象可能让直观业务分支更难修改。整洁不是终点；先观察真实变化模式，再决定哪些重复值得合并。",
  "the-wet-codebase": "严格追求 DRY 可能把相似但不同的逻辑强行绑在一起。适度重复保留独立演进空间，抽象须证明能降低总复杂度。",
  "npm-audit-broken-by-design": "作者批评默认安全告警缺乏可利用性与运行环境的上下文，易制造告警疲劳；应区分真实可达风险与构建链报告。",
  "how-does-the-development-mode-work": "开发模式可运行昂贵但有价值的警告，生产模式去掉额外开销；构建边界必须明确，避免把调试逻辑带到线上。",
  "suppressions-of-suppressions": "一次 lint 或类型规则豁免可能合理，但豁免之上的再次豁免值得单独审查；显式追踪例外比无限放宽门禁稳妥。",
  "how-to-fix-any-bug": "修 bug 时先做可复现案例，再逐项删去无关代码，直到只剩根因；用实验收窄问题比不断叠加猜测有效。",
  "a-chain-reaction": "界面从作者的代码与数据出发，经过一连串转换才出现在读者屏幕；RSC 的关键问题是这些转换发生在哪台机器、哪个阶段。",
  "the-two-reacts": "同一 UI 程序跨设备运行；关键不是简单选 SSR 或 CSR，而是决定组件计算怎样在两侧切分、传递与接续。",
  "react-for-two-computers": "用两台计算机理解 React：一部分 UI 计算先在服务端执行，另一部分在浏览器接管交互，边界需要明确的数据与代码传递。",
  "jsx-over-the-wire": "从 API 返回视图模型，走向可组合的 UI 描述，是为了更贴近地组织取数与展示；跨网络传 JSX 仍须处理参数与序列化。",
  "impossible-components": "同时需要服务端文件读取和客户端本地状态的组件不能在单一环境直接执行；拆成 Server 与 Client Components 才能明确职责。",
  "what-does-use-client-do": "use client 与 use server 标记跨运行环境的入口，不只是给文件贴标签；它们让代码与调用跨过时间、空间和模块边界。",
  "functional-html": "把 HTML 标签逐步扩展为可调用、可组合、可异步的函数，可从另一条路理解 RSC：服务端准备内容，客户端负责交互。",
  "rsc-for-astro-developers": "Astro 组件与交互 Island 的分工可帮助理解 RSC 的 Server/Client Components：前者预处理并向下传数据，后者负责浏览器交互。",
  "static-as-a-server": "Server Component 的 server 指执行环境，不要求每次访问都启动常驻服务；构建期执行也能输出静态资源。",
  "one-roundtrip-per-navigation": "导航取数既要就近声明需求，也要避免请求瀑布；作者比较 HTML、REST、loader、GraphQL 与 RSC 的组合性和往返成本。",
  "why-does-rsc-integrate-with-a-bundler": "RSC 不只序列化数据，还须传客户端代码引用；与模块系统和 bundler 集成，才能让两端正确识别、加载组件。",
  "progressive-json": "普通 JSON 往往等整个对象传完才能解析；渐进式协议可先交付可用部分，再补齐慢数据。流式处理的是阻塞关系。",
  "rsc-for-lisp-developers": "借 Lisp 的代码即数据视角看 RSC：元素可先作为描述传递，再由另一端解释；这只是有边界的类比，并非同一机制。",
  "how-imports-work-in-rsc": "RSC 扩展 import/export 来组织跨端程序；use client/use server 边界决定模块在哪端执行，错误依赖应在构建期暴露。",
  "introducing-rsc-explorer": "RSC Explorer 用交互样例展示 React 树的序列化与反序列化；协议是内部实现，不能把当前格式当作稳定公开 API。",
  "open-social": "开放社交的价值不止开源客户端，而是身份、数据、关系与传播范围跨产品延续；协议让竞争回到产品体验。",
  "where-its-at": "逐步拆解 at:// URI：从 handle 找稳定身份，再定位托管处和 JSON 记录。身份与托管分离是迁移后地址不变的关键。",
  "a-social-filesystem": "把社交内容视作用户拥有的记录、集合与链接，应用只是组合这些数据的不同视图；共享数据层能减少平台锁定。",
  "there-are-no-instances-in-atproto": "atproto 不能套用 Mastodon 的实例模型；托管、身份和应用分离。应看用户能否迁移身份与数据，而非实例数量。",
  "algebraic-effects-for-the-rest-of-us": "代数效应提供声明所需效果、由外层决定处理方式的心智模型；可借此理解 React 的某些控制流，但不能说 JS 已原生支持。",
  "the-math-is-haunted": "Lean 把命题和证明写成可检查的代码，让数学推理能够组合和机器验证；作者从简单例子体验形式化证明。",
  "beyond-booleans": "在 Lean 中命题可成为类型、证明成为该类型的值；相比只返回 true/false，它保留了可组合的证据。",
  "a-lean-syntax-primer": "从定义、类型、函数、命名空间到证明脚本，建立 Lean 语法入门地图；它是作者的学习速览，不是完整规范。",
  "how-i-vibed-a-proof-of-conways-conjecture": "作者记录 AI 辅助探索 Conway 猜想 Lean 证明：选题、失败、实验环境与核查都不能省；结论须保留验证边界。",
  "things-i-dont-know-as-of-2018": "公开知识盲区不会否定已有能力；说清不会什么，能减少权威光环带来的误判，也让后续学习更有方向。",
  "fix-like-no-ones-watching": "技术债也藏在阻止人顺手改进的细小摩擦中；降低修复门槛，探索和改良才更容易持续。",
  "coping-with-feedback": "发布后的反馈混合真实问题、个人偏好和情绪压力；先分清可行动信号与噪声，再安排回应节奏。",
  "name-it-and-they-will-come": "新想法常难讨论，因为大家尚未命名其痛点；准确命名有助协作、检验和传播，但不能用口号替代证据。",
  "preparing-for-tech-talk-part-1-motivation": "准备技术演讲先问为何要讲、讲给谁听，再决定题目；明确听众价值，后续设计才有方向。",
  "preparing-for-tech-talk-part-2-what-why-and-how": "做幻灯片前先定 What、Why、How：要传达什么，为什么重要，怎样让听众理解；清晰骨架能减少返工。",
  "preparing-for-tech-talk-part-3-content": "先自上而下列演讲提纲，再自下而上打磨最有力量的片段，并用多轮试讲修正节奏与信息密度。",
  "my-decade-in-review": "作者按年份回顾求学、工作与开源经历；职业路径受机会、协作和偶然性影响，并非可复制的成功公式。",
  "im-doing-a-little-consulting": "作者在离开 Meta、参与 Bluesky 后说明阶段性咨询计划与擅长领域；这是职业选择说明，不是技术成果介绍。",
  "hire-me-in-japan": "作者概述 React、React Native 与开源工作，并明确希望赴日工作的条件；这篇是求职说明，不是技术教程。",
};
